#set-option -g status on
#set-option -g status-interval 2
#set-option -g status-justify "centre"
#set-option -g status-left-length 60
#set-option -g status-right-length 90
#set-option -g status-left "#( ~/.config/tmux/tmux-powerline/powerline.sh left)"
#set-option -g status-right "#(~/.config/tmux/tmux-powerline/powerline.sh right)"

#bind C-[ run '~/path/to/tmux-powerline/mute_powerline.sh left'		# Mute left statusbar.
#bind C-] run '~/path/to/tmux-powerline/mute_powerline.sh right'		# Mute right statusbar.

set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-a
bind C-a send-prefix
