#!/bin/sh

#export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#export WORKON_HOME=$HOME/.virtualenvs
#export VIRTUALENVWRAPPER_VIRTUALENV=$HOME/.local/bin/virtualenv
#source $HOME/.local/bin/virtualenvwrapper.sh
#workon jp >/dev/null

python -m venv ./.venv
