#! /bin/sh

sxhkd  &

[[ "$(xrandr --query | grep 'HDMI-1')" = *disconnected* ]] && \

    {   bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 ;
        killall -q polybar;
        polybar --reload eDP1; } || \

    {   bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 ;
	    bspc monitor eDP-1  -d 9 10 ;
	    xrandr  --output HDMI-1 --mode 1920x1080 --rotate normal \
                --output eDP-1  --mode 1920x1080 --rotate normal --below HDMI-1 ; }

bspc config border_width         1
bspc config window_gap           8

#bspc config initial_polarity first_child
bspc config focus_follows_pointer       true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config normal_border_color         "#424242"
bspc config focused_border_color        "#00FFFF"
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
#bspc window --presel right

bspc rule -a Zathura        state=tiled
bspc rule -a Emacs          state=tiled
bspc rule -a '*:albert'     focus=on
bspc rule -a '*:unimatrix'  state=fullscreen
bspc rule -a '*:guake'      state=floating focus=on

picom -b &
dunst &
nm-applet &
albert &
unclutter --ignore-scrolling --timeout 2 &
redshift -x
redshift -O 3600
xset s off
killall -SIGUSR1 dunst
#nitrogen --restore &
#guake &
