#!/bin/bash

make clean && rm -f config.h && rm -f *.orig &&
git reset --hard origin/master && 
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ] && [ "$branch" != "config" ] ;then
		echo $branch
		git merge $branch -m $branch
	fi
done &&
#git merge rmaster      -m rmaster      &&
git merge config       -m config       &&

make && sudo make clean install
