#! /bin/sh

# check if bspwm is running:
pgrep bspwm > /dev/null || exit 0

monitor_add() {
    # Add the external monitor
    xrandr  --output HDMI-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
            --output eDP-1            --mode 1920x1080 --pos 0x0    --rotate normal --below HDMI-1

    n_desktops=8 # How many desktops should be on second monitor

    for desktop in $(bspc query -D -m eDP-1 | sed "$n_desktops"q)
    do
        bspc desktop $desktop --to-monitor HDMI-1
    done

    # The desktop "Desktop" is removed
    bspc desktop Desktop --remove > /dev/null

    sleep 2

    polybar --reload eDP1 &
    polybar --reload HDMI1 &
}

monitor_remove() {
    # Check if a single monitor is registerd by bspwm
    if [[ "$(bspc query -M | wc -l)" = 1 ]]
    then
        # Then do nothing
        exit
    fi
    bspc monitor eDP-1 -a Desktop > /dev/null

    for desktop in $(bspc query -D -m eDP-1)
    do
        bspc desktop $desktop --to-monitor HMDI-1
    done

    # Swap desktops

    bspc monitor HDMI-1 -a Desktop

    for desktop in $(bspc query -D -m HDMI-1)
    do
        bspc desktop $desktop --to-monitor eDP-1
    done
    
    bspc monitor HDMI-1 --remove > /dev/null

    xrandr  --output HDMI-1 --off \
            --output eDP-1 \
            --primary \
            --mode 1920x1080 \
            --pos 0x0 \
            --rotate normal

    bspc desktop Desktop -r
 
    sleep 2

    polybar --reload eDP1 &
}

if xrandr | grep -o "HDMI-1 connected" > /dev/null && [[ "$1" != "1" ]] && [[ "$(bspc query -M | wc -l)" != 2 ]]
then
    monitor_add
else
    monitor_remove
fi
