#!/bin/bash

cmd_horizontal()
{
    [[ "$(xrandr --query | grep 'HDMI-1')" = *disconnected* ]] && laptop || \
    
        {   bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 ;
    	    bspc monitor eDP-1  -d 9 10 ;
    	    xrandr  --output HDMI-1 --primary   --mode 1920x1080 --rotate normal \
                    --output eDP-1              --mode 1920x1080 --rotate normal --below HDMI-1 ;
            killall -q polybar;
            polybar --reload HDMI1 &
            polybar --reload eDP1  &
            disown ; } 
}

cmd_vertical()
{
    [[ "$(xrandr --query | grep 'HDMI-1')" = *disconnected* ]] && laptop || \
    
        {   bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 ;
    	    bspc monitor eDP-1  -d 9 10 ;
    	    xrandr  --output HDMI-1 --primary   --mode 1920x1080 --rotate left \
                    --output eDP-1              --mode 1920x1080 --rotate normal --below HDMI-1 ;
            configs
            killall -q polybar;
            polybar --reload HDMI1 &
            polybar --reload eDP1  &
            disown ; } 
}

laptop()
{
    bspc monitor "$(bspc query -M | sed -n 1p)" -r;
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 ;
    configs
    killall -q polybar;
    polybar --reload eDP1 &
    disown ;
}

configs()
{
    bspc config border_width         1
    bspc config window_gap           8
    
    #bspc config initial_polarity first_child
    bspc config focus_follows_pointer       true
    bspc config split_ratio                 0.50
    bspc config borderless_monocle          true
    bspc config gapless_monocle             true
    bspc config single_monocle              true
    bspc config normal_border_color         "#424242"
    bspc config focused_border_color        "#00FFFF"
    bspc config remove_unplugged_monitors   true
    bspc config remove_disabled_monitors    true
    #bspc window --presel right
    
    bspc rule -a Zathura        state=tiled
    bspc rule -a Emacs          state=tiled
    bspc rule -a '*:albert'     focus=on
    bspc rule -a '*:unimatrix'  state=fullscreen
    bspc rule -a '*:guake'      state=floating focus=on
}

case "$1" in 
    horizontal) cmd_horizontal       ;;
    vertical  ) cmd_vertical         ;;
    *         ) echo "wrong usage"   ;;
esac

exit 0
