#!/bin/bash

entry="$( { find -L   \
        ~/Documents     \
        ~/Downloads     \
        ~/Movies        \
        ~/Videos        \
        -type f | rofi -sort true -sorting-method fzf -dmenu -i -p open ; } || echo"" )"

[[ -z "$entry" ]] && exit 

case $(file --mime-type "$entry" -bL) in

    text/html)
        brave "$entry"
        ;;

    text/* | inode/x-empty | application/json | application/octet-stream)
        st -e vim "$entry"
        ;;

    video/*)
        vlc "$entry"
        ;;

    application/pdf | application/postscript)
        zathura "$entry"
        ;;

esac
