#!/bin/zsh

rsync -avu --delete ~/.zshrc            ~/git/.dotfiles
rsync -avu --delete ~/.localrc          ~/git/.dotfiles
rsync -avu --delete ~/.vimrc            ~/git/.dotfiles
rsync -avu --delete ~/.dwm              ~/git/.dotfiles
rsync -avu --delete ~/.tmux.conf        ~/git/.dotfiles
rsync -avu --delete ~/.scripts          ~/git/.dotfiles
rsync -avu --delete ~/.config/sxhkd     ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/bspwm     ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/i3        ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/i3status  ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/spectrwm  ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/alacritty ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/kitty     ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/tmux      ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/st        ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/dunst     ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/zathura   ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/polybar   ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/rofi      ~/git/.dotfiles/.config
rsync -avu --delete ~/.config/albert    ~/git/.dotfiles/.config


cd ~/git/.dotfiles

git add --all &&
git commit -a -m "update" &&
git push origin master &&

cd -
