#!/bin/zsh

# to create a virtual environment in the current directory with the name 'virtual'
python3 -m venv virtual

# to activate it
source virtual/bin/activate

# to deactivate
deactivate

---------------------------------------------------

pip install jupyter numpy matplotlib numba pandas jupyterthemes scipy xlrd

jt -t gruvboxd -fs 95 -altp -tfs 11 -nfs 115 -cellw 88% -T

pip install jupyter_contrib_nbextensions

jupyter contrib nbextension install --user

pip install jupyter_nbextensions_configurator

jupyter nbextensions_configurator enable --user

----------------------------------------------------

cd $HOME/.ipython/profile_default/startup

printf '%s\n' 'from jupyterthemes import jtplot' 'jtplot.style(theme='gruvboxd')' >startup.ipy

cd
