#!/bin/bash

cd ~/shared

entry="$( { find . -type f | grep -v "$RECYCLE.BIN\|System Volume Information" | dmenu -i -l 10 -p "open" ; } || echo"" )"

[[ -z "$entry" ]] && exit 

case $(file --mime-type "$entry" -bL) in

    text/html)
        brave "$entry"
        ;;

    text/* | inode/x-empty | application/json | application/octet-stream)
        st -e vim "$entry"
        ;;

    video/*)
        vlc "$entry"
        ;;

    application/pdf | image/vnd.djvu | application/postscript)
        zathura "$entry"
        ;;

esac
