#!/bin/bash

declare options=("suspend
shutdown
reboot
escswap
redshift
display")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'run')

case "$choice" in
	suspend)
		slock & systemctl suspend
	;;
	shutdown)
		shutdown now
	;;
	reboot)
		reboot
	;;
	escswap)
		~/.scripts/escswap
	;;
	redshift)
		redshift -x && redshift -O 3600
	;;
	display)
		xrandr  --output HDMI1 --mode 1920x1080 --rotate normal --output eDP1  --mode 1920x1080 --rotate normal --right-of HDMI1
	;;
                
	*)
		exit 1
	;;
esac
