#!/bin/bash

declare options=("suspend
shutdown
reboot
escswap
redshift")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'run')

case "$choice" in
	suspend)
		slock & systemctl suspend
	;;
	shutdown)
		shutdown now
	;;
	reboot)
		reboot
	;;
	escswap)
		~/.scripts/escswap
	;;
	redshift)
		redshift -x && redshift -O 3600
	;;
	*)
		exit 1
	;;
esac
